import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDown, ArrowLeft, ArrowUp, Clock3, Cpu, Gauge, HardDrive, MemoryStick, Search, Server, Wifi } from "lucide-react";
import { useLiveData } from "@/contexts/LiveDataContext";
import { useNodeList, type NodeBasicInfo } from "@/contexts/NodeListContext";
import type { Record as LiveRecord } from "@/types/LiveData";
import "./TwilightInstance.css";

const demoNode=(uuid:string,name:string,region:string,group:string):NodeBasicInfo=>({uuid,name,region,group,cpu_name:"AMD EPYC 7B13",virtualization:"KVM",arch:"amd64",cpu_cores:4,os:"Debian 12",kernel_version:"6.8",gpu_name:"",mem_total:8*1024**3,swap_total:2*1024**3,disk_total:120*1024**3,version:"1.0",weight:0,price:0,tags:"",billing_cycle:0,currency:"",traffic_limit:0,traffic_limit_type:undefined,expired_at:"",created_at:"",updated_at:""});
const DEMO=[demoNode("demo-sin","新加坡-Edge","Singapore, SG","Asia"),demoNode("demo-sin-2","新加坡-Core","Singapore, SG","Asia"),demoNode("demo-tokyo","东京","Tokyo, JP","Asia"),demoNode("demo-fra","法兰克福","Frankfurt, DE","Europe")];
const fmt=(bytes=0)=>{if(!bytes)return"0 B";const u=["B","KB","MB","GB","TB"],i=Math.min(4,Math.floor(Math.log(bytes)/Math.log(1024)));return`${(bytes/1024**i).toFixed(i>1?1:0)} ${u[i]}`};
const uptime=(s=0)=>`${Math.floor(s/86400)}天 ${Math.floor(s%86400/3600)}小时`;
const tone=(v:number)=>v>=85?"critical":v>=65?"warning":"healthy";

export default function InstancePage(){
  const {uuid}=useParams<{uuid:string}>();const navigate=useNavigate();const {nodeList}=useNodeList();const {live_data}=useLiveData();const [recent,setRecent]=useState<LiveRecord[]>([]);const [query,setQuery]=useState("");
  const nodes=nodeList?.length?nodeList:import.meta.env.DEV?DEMO:[];const node=nodes.find(n=>n.uuid===uuid)||nodes[0];const live=live_data?.data;const record=node?live?.data?.[node.uuid]:undefined;const online=new Set(live?.online||[]);const isDemo=Boolean(node?.uuid.startsWith("demo-"));
  useEffect(()=>{if(!uuid||uuid.startsWith("demo-")){setRecent([]);return}const c=new AbortController();fetch(`/api/recent/${uuid}`,{signal:c.signal}).then(r=>r.json()).then(r=>setRecent((r?.data||[]).slice(-90))).catch(()=>{});return()=>c.abort()},[uuid]);
  const chartData=useMemo(()=>{const source=recent.length?recent:Array.from({length:30},(_,i)=>({cpu:{usage:28+Math.sin(i/3)*12+i*.25},ram:{used:(3.2+Math.sin(i/5)*.35)*1024**3},network:{up:(220+Math.sin(i/2)*80)*1024,down:(150+Math.cos(i/3)*55)*1024},updated_at:new Date(Date.now()-(29-i)*60000).toISOString()} as LiveRecord));return source.map((r,i)=>({time:new Date(r.updated_at||Date.now()).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),cpu:r.cpu?.usage||0,memory:node?.mem_total?r.ram.used/node.mem_total*100:0,up:(r.network?.up||0)/1024,down:(r.network?.down||0)/1024,index:i}))},[recent,node?.mem_total]);
  if(!node)return <main className="ti-shell"><div className="ti-empty">未找到节点</div></main>;
  const cpu=Math.round(record?.cpu?.usage??chartData.at(-1)?.cpu??0),memory=Math.round(record&&node.mem_total?record.ram.used/node.mem_total*100:chartData.at(-1)?.memory??0),isOnline=isDemo||online.has(node.uuid);
  const filtered=nodes.filter(n=>`${n.name} ${n.region} ${n.group}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="ti-shell">
    <div className="ti-background"/><header className="ti-header"><button onClick={()=>navigate("/")}><ArrowLeft size={18}/>返回星图</button><div><Server size={21}/><strong>Komari</strong><span>节点详情</span></div><span className={isOnline?"online":"offline"}><i/>{isOnline?"实时在线":"当前离线"}</span></header>
    <div className="ti-layout"><section className="ti-main"><div className="ti-title"><div><p>{node.group||"GLOBAL NODE"} · {node.region}</p><h1>{node.name}</h1><span>{node.uuid}</span></div><div className="ti-uptime"><Clock3/><small>运行时间</small><strong>{uptime(record?.uptime||18*86400+7*3600)}</strong></div></div>
      <div className="ti-kpis"><Kpi icon={Cpu} label="CPU" value={`${cpu}%`} tone={tone(cpu)}/><Kpi icon={MemoryStick} label="内存" value={`${memory}%`} tone={tone(memory)}/><Kpi icon={HardDrive} label="磁盘" value={fmt(record?.disk?.used||42*1024**3)}/><Kpi icon={Gauge} label="负载 1m" value={(record?.load?.load1??.72).toFixed(2)}/></div>
      <ChartCard title="系统负载趋势" subtitle="CPU 与内存 · 最近 30 个采样"><ResponsiveContainer width="100%" height={230}><AreaChart data={chartData}><defs><linearGradient id="cpuFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#62d7ff" stopOpacity={.35}/><stop offset="100%" stopColor="#62d7ff" stopOpacity={0}/></linearGradient><linearGradient id="memFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f6b44f" stopOpacity={.25}/><stop offset="100%" stopColor="#f6b44f" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(140,174,211,.12)" vertical={false}/><XAxis dataKey="time" tick={{fill:"#71839d",fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={[0,100]} tick={{fill:"#71839d",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#071a30",border:"1px solid #294763",borderRadius:8}}/><Area type="monotone" dataKey="cpu" name="CPU %" stroke="#62d7ff" fill="url(#cpuFill)" strokeWidth={2}/><Area type="monotone" dataKey="memory" name="内存 %" stroke="#f6b44f" fill="url(#memFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></ChartCard>
      <div className="ti-bottom"><ChartCard title="网络吞吐" subtitle="KB/s"><ResponsiveContainer width="100%" height={170}><AreaChart data={chartData}><CartesianGrid stroke="rgba(140,174,211,.1)" vertical={false}/><XAxis dataKey="time" hide/><YAxis hide/><Tooltip contentStyle={{background:"#071a30",border:"1px solid #294763",borderRadius:8}}/><Area type="monotone" dataKey="up" name="上行" stroke="#65dfa6" fill="#65dfa622"/><Area type="monotone" dataKey="down" name="下行" stroke="#62cfff" fill="#62cfff18"/></AreaChart></ResponsiveContainer><div className="ti-network-values"><span><ArrowUp/> {fmt(record?.network?.up||286*1024)}/s</span><span><ArrowDown/> {fmt(record?.network?.down||182*1024)}/s</span></div></ChartCard><div className="ti-specs"><h2>节点配置</h2><Spec label="处理器" value={`${node.cpu_name} · ${node.cpu_cores} 核`}/><Spec label="系统" value={`${node.os} · ${node.arch}`}/><Spec label="虚拟化" value={node.virtualization}/><Spec label="内存" value={fmt(node.mem_total)}/><Spec label="磁盘" value={fmt(node.disk_total)}/></div></div>
    </section><aside className="ti-sidebar"><div className="ti-side-head"><div><small>NETWORK</small><h2>节点列表</h2></div><span>{nodes.length}</span></div><label className="ti-side-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索节点"/></label><div className="ti-node-list">{filtered.map(n=>{const active=n.uuid===node.uuid,on=isDemo||n.uuid.startsWith("demo-")||online.has(n.uuid);return <button key={n.uuid} className={active?"active":""} onClick={()=>navigate(`/instance/${n.uuid}`)}><i className={on?"online":"offline"}/><span><b>{n.name}</b><small>{n.region||n.group}</small></span><em>{on?"在线":"离线"}</em></button>})}</div><div className="ti-side-foot"><Wifi size={16}/><span>实时数据每 2 秒刷新</span></div></aside></div>
  </main>
}

function Kpi({icon:Icon,label,value,tone:color=""}:{icon:typeof Cpu;label:string;value:string;tone?:string}){return <div className={`ti-kpi ${color}`}><Icon/><span>{label}</span><strong>{value}</strong></div>}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="ti-chart"><header><h2>{title}</h2><span>{subtitle}</span></header>{children}</section>}
function Spec({label,value}:{label:string;value:string}){return <div className="ti-spec"><span>{label}</span><strong>{value||"—"}</strong></div>}
